In [2]:
import numpy as np

In [3]:
my_list1 = [1,2,3,4]

In [4]:
my_array = np.array(my_list1)

In [5]:
type(my_list1)

list

In [6]:
my_list2 = [11,22,33,44]

In [7]:
my_list = [my_list1,my_list2]

In [8]:
my_list

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np.array(my_list)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.reshape(4,2)

array([[ 1,  2],
       [ 3,  4],
       [11, 22],
       [33, 44]])

In [12]:
my_array2.shape

(2, 4)

In [13]:
type(my_array2)

numpy.ndarray

In [14]:
my_array2.dtype

dtype('int32')

In [15]:
np.zeros([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [17]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [18]:
np.arange(1,11,1).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
arr1 = np.arange(15)

In [22]:
arr1 = arr1.reshape(3,5)

In [23]:
arr1 * arr1

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [24]:
arr1 - arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
arr1*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [26]:
1/arr1

C:\Users\Aswathi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111],
       [ 0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857]])

In [27]:
arr1[:] = 99

In [28]:
arr1

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [29]:
arr1[1:5] = 10

In [30]:
arr1

array([[99, 99, 99, 99, 99],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [31]:
arr1[0:] = 20

In [32]:
arr1

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [33]:
arr1[:,1:2] = 10

In [34]:
arr1

array([[20, 10, 20, 20, 20],
       [20, 10, 20, 20, 20],
       [20, 10, 20, 20, 20]])

In [35]:
arr1[2:,4:] = 11

In [36]:
arr1

array([[20, 10, 20, 20, 20],
       [20, 10, 20, 20, 20],
       [20, 10, 20, 20, 11]])

In [37]:
arr1[1:2,1:2] = 89

In [38]:
arr1

array([[20, 10, 20, 20, 20],
       [20, 89, 20, 20, 20],
       [20, 10, 20, 20, 11]])

In [40]:
arr1[1:2,1:2]

array([[89]])

In [41]:
arr1[1][1]

89

In [43]:
arr2d = np.zeros([10,10])

In [44]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [45]:
len(arr2d)

10

In [46]:
arr2d[[2,4,6,8]]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [47]:
arr2d.T

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [48]:
arr3 = np.arange(60).reshape(12,5)

In [49]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [50]:
arr3.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [52]:
np.dot(arr3.T,arr3)

array([[12650, 12980, 13310, 13640, 13970],
       [12980, 13322, 13664, 14006, 14348],
       [13310, 13664, 14018, 14372, 14726],
       [13640, 14006, 14372, 14738, 15104],
       [13970, 14348, 14726, 15104, 15482]])

In [53]:
arr3.swapaxes(1,0)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [55]:
arr3.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [56]:
np.sqrt(arr3)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ],
       [ 3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739],
       [ 3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894],
       [ 4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949],
       [ 5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481],
       [ 5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189],
       [ 5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ],
       [ 6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958],
       [ 6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ],
       [ 7.07106781,  7.14142843,  7.21110255,  7.28010989,  7.34846923],
       [ 7.41619849,  7.48331477,  7.54983444,  7.61577311,  7.68114575]])

In [62]:
from numpy import random

arr4 = np.random.randn(10,10)

In [63]:
arr4

array([[-1.21329694, -0.62911748,  2.07209317,  1.42335755, -1.63020296,
         0.54145348, -0.60488704,  0.76936926,  0.73464378,  1.20136869],
       [-0.71982966, -0.85655743,  1.29630612,  2.01392417,  1.15639525,
        -0.35384878, -0.36530569,  0.46174798, -2.88742914, -1.99973658],
       [-0.97220282,  0.13560097, -0.59204625, -0.5815732 ,  1.99905223,
        -0.42848973,  0.41885159, -0.26315913,  0.26552696,  0.71638841],
       [ 0.32352481,  0.82546989, -0.22605173, -0.5051303 ,  0.31655951,
        -1.35334383, -1.16701502,  0.21406371,  0.08020631,  0.41258165],
       [-1.21642442, -1.77705651, -1.36276824,  0.64570669, -0.81369584,
         0.72312877, -0.64400664,  1.65249276,  0.81087154,  1.38829298],
       [-0.20726097, -0.70591764, -0.40547419, -0.23605019, -0.03497301,
        -0.80814242,  0.25190707,  0.29279804,  1.31995151, -2.13078415],
       [-1.66001742,  0.14507433,  0.9820188 ,  1.95330697, -1.21284113,
        -0.73102043, -1.20983974,  0.77713841

In [64]:
arr4 + arr4

array([[-2.42659388, -1.25823496,  4.14418634,  2.8467151 , -3.26040592,
         1.08290696, -1.20977408,  1.53873852,  1.46928755,  2.40273738],
       [-1.43965933, -1.71311487,  2.59261225,  4.02784833,  2.31279049,
        -0.70769755, -0.73061139,  0.92349595, -5.77485829, -3.99947315],
       [-1.94440563,  0.27120194, -1.18409251, -1.16314639,  3.99810445,
        -0.85697946,  0.83770318, -0.52631827,  0.53105392,  1.43277682],
       [ 0.64704963,  1.65093979, -0.45210346, -1.01026059,  0.63311902,
        -2.70668766, -2.33403004,  0.42812742,  0.16041262,  0.8251633 ],
       [-2.43284884, -3.55411301, -2.72553649,  1.29141339, -1.62739168,
         1.44625754, -1.28801328,  3.30498553,  1.62174307,  2.77658597],
       [-0.41452194, -1.41183528, -0.81094837, -0.47210038, -0.06994602,
        -1.61628485,  0.50381413,  0.58559607,  2.63990302, -4.2615683 ],
       [-3.32003485,  0.29014867,  1.96403759,  3.90661394, -2.42568227,
        -1.46204087, -2.41967948,  1.55427682

In [65]:
np.add(arr4,arr4)

array([[-2.42659388, -1.25823496,  4.14418634,  2.8467151 , -3.26040592,
         1.08290696, -1.20977408,  1.53873852,  1.46928755,  2.40273738],
       [-1.43965933, -1.71311487,  2.59261225,  4.02784833,  2.31279049,
        -0.70769755, -0.73061139,  0.92349595, -5.77485829, -3.99947315],
       [-1.94440563,  0.27120194, -1.18409251, -1.16314639,  3.99810445,
        -0.85697946,  0.83770318, -0.52631827,  0.53105392,  1.43277682],
       [ 0.64704963,  1.65093979, -0.45210346, -1.01026059,  0.63311902,
        -2.70668766, -2.33403004,  0.42812742,  0.16041262,  0.8251633 ],
       [-2.43284884, -3.55411301, -2.72553649,  1.29141339, -1.62739168,
         1.44625754, -1.28801328,  3.30498553,  1.62174307,  2.77658597],
       [-0.41452194, -1.41183528, -0.81094837, -0.47210038, -0.06994602,
        -1.61628485,  0.50381413,  0.58559607,  2.63990302, -4.2615683 ],
       [-3.32003485,  0.29014867,  1.96403759,  3.90661394, -2.42568227,
        -1.46204087, -2.41967948,  1.55427682

In [67]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])